variables:
  IMAGE_NAME: "intent-classifier-gitlab"
  IMAGE_VERSION: "latest"
  BUILD_ARGS: "-f core/Dockerfile ."
  SHARED_DATA_PATH: "/opt/jenkins_mlflow_gitlab"
  SHARED_DIR_MOUNT_POINT: "/shared_dir"

stages:
  - build
  - train

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Docker 이미지를 빌드합니다..."
    - docker build -t $IMAGE_NAME:$IMAGE_VERSION $BUILD_ARGS
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'

run_training:
  stage: train
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "학습 컨테이너를 실행합니다..."
    - >
      docker run --rm
      -v "$SHARED_DATA_PATH$SHARED_DIR_MOUNT_POINT:$SHARED_DIR_MOUNT_POINT"
      --user 0:0
      $IMAGE_NAME:$IMAGE_VERSION
      sh -c "cd /app && uv run -m main"
  needs:
    - build_docker_image