stages:
  - build
  - train

variables:
  - IMAGE_TAG: intent-classifier
  - IMAGE_DEFAULT_VERSION: latest
  - CUR_DIR: /opt/jenkins_mlflow_gitlab/
  - GLOBAL_DATA_MOUNT_POINT: data
  - SHARED_DIR_MOUNT_POINT: /shared_dir/

build-job:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
  script:
    - docker build -f core/Dockerfile -t $IMAGE_TAG:$IMAGE_DEFAULT_VERSION .

train-job:
  stage: train
  script:
    - docker run -d -v ${CUR_DIR}${GLOBAL_DATA_MOUNT_POINT}${SHARED_DIR_MOUNT_POINT}:${SHARED_DIR_MOUNT_POINT} --user 0:0 $IMAGE_TAG:$IMAGE_DEFAULT_VERSION

# 작성중