pipeline {
    agent any

    stages {
        // stage('Checkout Source Code') {
        //     steps {
        //         echo 'Git 리포지토리에서 소스코드를 가져옵니다...'
        //     }
        // }
        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Docker 이미지를 빌드합니다...'
                    def customImage = docker.build('intent-classifier:latest', '-f core/Dockerfile .')
                }
            }
        }
        stage('Run Training') {
            steps {
                script {
                    echo '학습 컨테이너를 실행합니다...'
                    customImage.run()
                }
            }
        }
    }
}