[project]
name = "example-intent-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "sentence-transformers>=5.1.0",
    "tqdm>=4.67.1",
]
