services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "${JENKINS_WEB_UI_PORT:-8081}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    restart: on-failure
    volumes:
      - ${GLOBAL_DATA_MOUNT_POINT}${JENKINS_DATA_MOUNT_POINT}:/var/jenkins_home
      - ${GLOBAL_DATA_MOUNT_POINT}${SHARED_DIR_MOUNT_POINT}:${SHARED_DIR_MOUNT_POINT}


  jenkins_agent:
    image: jenkins/inbound-agent:latest
    container_name: docker-agent
    restart: always
    environment:
      - JENKINS_URL=http://${JENKINS_HOST_IP}:2454
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      - JENKINS_WEB_SOCKET=${JENKINS_WEB_SOCKET}
    volumes:
      - ${HOST_DOCKER_SOCKET_PATH}:/var/run/docker.sock
      - ${GLOBAL_DATA_MOUNT_POINT}${SHARED_DIR_MOUNT_POINT}:${SHARED_DIR_MOUNT_POINT}
      

