[project]
name = "13-httpx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.2",
    "httpx>=0.28.1",
    "pydantic>=2.12.3",
    "requests>=2.32.5",
    "uvicorn[all]>=0.38.0",
]
